# Generated by Django 5.2.6 on 2025-09-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
