# Generated by Django 5.2.6 on 2025-09-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usermodel_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
