# Generated by Django 5.2.6 on 2025-09-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usermodel_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_name',
            field=models.CharField(default='abc', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
