# Generated by Django 5.2.6 on 2025-09-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usermodel_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'User_table', 'verbose_name_plural': 'Users_table'},
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='users_table',
        ),
    ]
