# Generated by Django 5.2.6 on 2025-09-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_usermodel_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
