# Generated by Django 5.2.6 on 2025-09-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_usermodel_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Viewer', 'Viewer')], default='Viewer', max_length=15),
        ),
    ]
