# Generated by Django 5.2.6 on 2025-09-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpmodel',
            old_name='user_id',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='user_email',
            field=models.EmailField(default='AA', max_length=100),
            preserve_default=False,
        ),
    ]
