# Generated by Django 5.2.6 on 2025-09-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_rename_user_id_otpmodel_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='otp_code',
            field=models.CharField(max_length=100),
        ),
    ]
