# Generated by Django 5.2.6 on 2025-09-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0004_alter_otpmodel_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='otp_code',
            field=models.CharField(max_length=100),
        ),
    ]
