# Generated by Django 4.2.7 on 2025-09-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0005_alter_otpmodel_otp_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpmodel',
            old_name='user_email',
            new_name='email',
        ),
    ]
