# Generated by Django 4.2.7 on 2025-09-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0006_rename_user_email_otpmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='otp_count',
            field=models.IntegerField(default=0),
        ),
    ]
