# Generated by Django 4.2.7 on 2025-09-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0007_otpmodel_otp_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpmodel',
            old_name='email',
            new_name='user_email',
        ),
    ]
